name: Java CI with Maven

on:
  push:
    branches: [ "origin" ]
  pull_request:
    branches: [ "origin" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package
      working-directory: project
      
    - name: Run tests with Maven
      id: test
      run: |
        set +e
        mvn test > result.log 2>&1
        test_exit_code=$?
        set -e
        if [ $test_exit_code -eq 0 ]; then
          echo "success=true" >> $GITHUB_ENV
        else
          echo "success=false" >> $GITHUB_ENV
        fi
      working-directory: project
    
    - name: Send Telegram notification
      if: always()
      run: |
        if [ "${{ env.success }}" == "true" ]; then
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Все ок"
        else
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Не пройдены следующие тесты: $(grep -A 1 'Tests run:' project/result.log)"
        fi
