name: Java CI with Maven

on:
  push:
    branches: [ "origin" ]
  pull_request:
    branches: [ "origin" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package
      working-directory: project
      
    - name: Run tests with Maven
      id: test
      run: |
        TEST_OUTPUT=$(mvn test 2>&1)
        echo "$TEST_OUTPUT"
        if echo "$TEST_OUTPUT" | grep -q 'BUILD SUCCESS'; then
          echo "::set-output name=success::true"
        else
          echo "::set-output name=success::false"
          TEST_RESULTS=$(echo "$TEST_OUTPUT" | grep -A 1 'Tests run:' || echo "No test summary found")
          echo "::set-output name=test_results::$TEST_RESULTS"
        fi
      working-directory: project
    
    - name: Send Telegram notification
      if: always()
      run: |
        echo "Success: ${{ steps.test.outputs.success }}"
        echo "Test Results: ${{ steps.test.outputs.test_results }}"
        if [ "${{ steps.test.outputs.success }}" == "true" ]; then
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Все ок"
        else
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Не пройдены следующие тесты: ${{ steps.test.outputs.test_results }}"
        fi
